version: "3.4"
# Define common behavior
x-qbt-queue-controller:
  &default-qbt-queue-controller
  build: 
    context: .
    args:
      BUILD_VERSION: ${BUILD_VERSION}
  # Other settings can also be shared
  image: dantebarba/qbt-queue-controller:latest

# Define one service by wanted tag
services:
  # Use the extension as is
  qbt-queue-latest:
    *default-qbt-queue-controller
  # Override the image tag
  qbt-queue-tag:
    << : *default-qbt-queue-controller
    image: dantebarba/qbt-queue-controller:${BUILD_VERSION}
    environment: 
      NZB_HOST: "nzbget"
      NZB_PORT: "6789"
      NZB_USERNAME: "nzbget"
      NZB_PASSWORD: "tegbzn6789"
  
  nzbget:
    image: ghcr.io/linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./config:/config
      - ./downloads:/downloads
    ports:
      - 6789:6789
    restart: unless-stopped